export interface SumaryOptions {
    Sales: Number,
    Total: Number,
}

export interface EntitySummaryReport {
    GrossSales?: SumaryOptions,
    LottoSales?: SumaryOptions, 
    OnlineLottery?: SumaryOptions,
    FeeSales?: SumaryOptions,
    HouseAccountPay?: SumaryOptions,
    Refunds?: SumaryOptions,
    Voids?: SumaryOptions,
    SaleTax?: SumaryOptions,
    TipsAmount?: SumaryOptions,
    NonTaxable?: SumaryOptions,
    ReturnExchange?: SumaryOptions,
    SaleRounding?: SumaryOptions,
    NetSales?: SumaryOptions,
    LottoPayout?: SumaryOptions,
    OnlinePayout?: SumaryOptions,
    CouponSale_Dollar?: SumaryOptions,
    CouponSale_Percent?: SumaryOptions,
    PromoCoupons?: SumaryOptions,
    CanceledSale?: SumaryOptions,   
    NoSale?: SumaryOptions,
    ManualPriceChange?: SumaryOptions,
    Cost?: SumaryOptions,
    Profit?: SumaryOptions,
    Cash?: SumaryOptions,
    Card?: SumaryOptions,
    CardFee?:SumaryOptions,
    Check?: SumaryOptions,
    Debit?: SumaryOptions,
    Ebt?: SumaryOptions,
    Gift?: SumaryOptions,
    SideCard?: SumaryOptions,
}